
services:
  fedi-summarizer:
    image: fedisummarizer:latest
    env_file: .env
    develop:
      watch:
        - path: main.py
          action: rebuild
        - path: requirements.txt
          action: rebuild
